# File: .github/workflows/update-pinned-repos.yml
name: Update Pinned Repositories

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  update-repos:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch pinned repositories
        id: fetch-repos
        run: |
          RESPONSE=$(curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            -H "Content-Type: application/json" \
            --data '{"query": "query { user(login: \"ejach\") { pinnedItems(first: 6, types: [REPOSITORY]) { nodes { ... on Repository { name description url languages(first: 1) { nodes { name color } } } } } } }"}' \
            https://api.github.com/graphql)

          echo "API Response: $RESPONSE"  # Debug output

          # Check if the response contains errors
          ERRORS=$(echo "$RESPONSE" | jq '.errors')
          if [ "$ERRORS" != "null" ]; then
            echo "API Errors: $ERRORS"
            exit 1
          fi

          # Extract pinned repositories from the response and save to a file
          echo "$RESPONSE" | jq '.data.user.pinnedItems.nodes' > pinned-repos-temp.json
          cat pinned-repos-temp.json  # Debug output

          # Set the content as an output variable
          PINNED_REPOS_CONTENT=$(cat pinned-repos-temp.json | jq -c '.')
          echo "PINNED_REPOS_CONTENT=$PINNED_REPOS_CONTENT" >> $GITHUB_ENV

      - name: Check for changes
        id: check-changes
        run: |
          # Check if pinned-repos.json exists
          if [ -f "pinned-repos.json" ]; then
            EXISTING_REPOS_CONTENT=$(cat pinned-repos.json | jq -c '.')
            echo "Existing Repos Content: $EXISTING_REPOS_CONTENT"  # Debug output
          else
            EXISTING_REPOS_CONTENT="[]"
            echo "No existing repos file found."  # Debug output
          fi

          # Compare existing repos with fetched repos
          if [ "$EXISTING_REPOS_CONTENT" != "${{ env.PINNED_REPOS_CONTENT }}" ]; then
            echo "Changes detected."
            echo "CHANGED=true" >> $GITHUB_ENV
          else
            echo "No changes detected."
            echo "CHANGED=false" >> $GITHUB_ENV
          fi

      - name: Update pinned-repos.json
        if: env.CHANGED == 'true'
        run: |
          mv pinned-repos-temp.json pinned-repos.json
          echo "Updated pinned-repos.json"  # Debug output

      - name: Commit and push changes
        if: env.CHANGED == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add pinned-repos.json
          git commit -m "Update pinned repositories"
          git push
